# Generated by Django 3.2.23 on 2023-12-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='StoreItem',
        ),
    ]
