# Generated by Django 3.2.23 on 2023-12-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_store_storeitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeitem',
            options={'verbose_name_plural': 'Store Items'},
        ),
        migrations.AddField(
            model_name='storeitem',
            name='size_option',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
