# Generated by Django 3.2.23 on 2024-01-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compute',
            old_name='item_a',
            new_name='item_1',
        ),
        migrations.RenameField(
            model_name='compute',
            old_name='item_b',
            new_name='item_2',
        ),
        migrations.RenameField(
            model_name='compute',
            old_name='item_c',
            new_name='item_3',
        ),
        migrations.RenameField(
            model_name='compute',
            old_name='item_d',
            new_name='item_4',
        ),
        migrations.RenameField(
            model_name='digital',
            old_name='item_a',
            new_name='item_1',
        ),
        migrations.RenameField(
            model_name='digital',
            old_name='item_b',
            new_name='item_2',
        ),
        migrations.RenameField(
            model_name='digital',
            old_name='item_c',
            new_name='item_3',
        ),
        migrations.RenameField(
            model_name='digital',
            old_name='item_d',
            new_name='item_4',
        ),
    ]
