# Generated by Django 3.2.23 on 2024-01-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20240105_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compute',
            options={'verbose_name_plural': 'Compute'},
        ),
        migrations.AlterModelOptions(
            name='digital',
            options={'verbose_name_plural': 'Digital'},
        ),
    ]
