# Generated by Django 3.2.23 on 2024-01-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('term_a', models.CharField(blank=True, max_length=8, null=True)),
                ('term_b', models.CharField(blank=True, max_length=8, null=True)),
                ('term_c', models.CharField(blank=True, max_length=8, null=True)),
                ('term_d', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price_a', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_b', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space.space')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deskspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price_a', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_b', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space.space')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
