# Generated by Django 3.2.23 on 2024-01-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20240103_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deskspace',
            old_name='termprices',
            new_name='pricing',
        ),
        migrations.RenameField(
            model_name='labspace',
            old_name='termprices',
            new_name='pricing',
        ),
    ]
