# Generated by Django 3.2.23 on 2024-01-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_auto_20240103_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskspace',
            name='price_a',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deskspace',
            name='price_b',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deskspace',
            name='price_c',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deskspace',
            name='price_d',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labspace',
            name='price_a',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labspace',
            name='price_b',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labspace',
            name='price_c',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labspace',
            name='price_d',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
