# Generated by Django 3.2.23 on 2024-01-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_auto_20240103_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={},
        ),
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='space',
            name='term_a',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='term_b',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='term_c',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='term_d',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
